workflows:
  default:
    name: Default workflow
    environment:
      node: 18.18.2
      xcode: latest
      cocoapods: default
    scripts:

    - name: Clean and remove iOS platform
      script: |
        cordova clean
        cordova platform remove ios || true

    - name: Install Cordova globally
      script: |
        npm install -g cordova

    - name: Install CocoaPods
      script: |
        sudo gem install cocoapods
        pod setup
        pod repo update

    - name: Remove CocoaPods master specs repo
      script: |
        pod repo remove master

    - name: Install npm dependencies
      script: |
        npm install
        cordova plugin add cordova-plugin-moodleapp
        cordova platform add ios

    - name: Install jq for language updates
      script: |
        brew install jq


    - name: Install and run cordova-res
      script: |
        npm i -g cordova-res
        cordova-res

    - name: Build iOS app with verbose logging
      script: |
        cordova platform add ios --save --verbose
        npm run prod:ios

    artifacts:
      - platforms/ios/**/*
