workflows:
  default:
    name: Default workflow
    environment:
      node: 18.18.2
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Cordova globally
        script: |
          npm install -g cordova

      - name: Install npm dependencies
        script: |
          npm install
          npm audit fix
          # Optional: If npm audit fix does not resolve all issues, use the following command with caution
          # npm audit fix --force

      - name: Add and configure Cordova plugins
        script: |
          cordova plugin add cordova-plugin-moodleapp || true
          cordova platform rm ios || true
          cordova platform add ios

      - name: Install CocoaPods and Dependencies
        script: |
          sudo gem install cocoapods
          pod setup
          pod repo update
          pod install

      - name: Install jq for language updates
        script: |
          brew install jq

      - name: Install and run cordova-res
        script: |
          npm install -g cordova-res
          cordova-res

      - name: Build iOS app with verbose logging
        script: |
          cordova platform add ios --save --verbose
          npm run prod:ios

    artifacts:
      - platforms/ios/**/*
