workflows:
  default:
    name: Default workflow
    environment:
      node: 18.18.2
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Cordova globally
        script: |
          npm install -g cordova

      - name: Install npm dependencies and Cordova plugins
        script: |
          npm install
          npm audit fix --force
          cordova plugin add cordova-plugin-moodleapp
          cordova platform add ios

      - name: Install CocoaPods and Dependencies
        script: |
          sudo gem install cocoapods
          pod setup
          pod repo update
          pod install

      - name: Install jq for language updates
        script: |
          brew install jq

      - name: Install and run cordova-res
        script: |
          npm install -g cordova-res
          cordova-res

      - name: Build iOS app with verbose logging
        script: |
          cordova platform add ios --save --verbose
          npm run prod:ios

    artifacts:
      - platforms/ios/**/*
