workflows:
  default:
    name: Default workflow
    environment:
      node: 18.18.2 # Configura la versión de Node.js que necesitas
      xcode: latest
      cocoapods: default # Habilita el uso de CocoaPods
    scripts:

    # Limpiar el proyecto y eliminar la plataforma iOS
      - name: Clean and remove iOS platform
        script: |
          cordova clean
          cordova platform remove ios || true

      - name: Install Cordova globally
        script: |
          npm install -g cordova

      - name: Install CocoaPods
        script: |
          sudo gem install cocoapods
          pod setup
          pod repo update

      - name: Install npm dependencies
        script: |
          npm install

      - name: Install jq for language updates
        script: |
          brew install jq # Usa Homebrew para instalar jq

      #- name: Update language packs
      #  script: |
      #    npm run lang:update-langpacks


      - name: Install and run cordova-res
        script: |
          npm i -g cordova-res
          cordova-res

      - name: Modify Xcode project settings
        script: |
        PLIST_PATH="platforms/ios/Formación virtual para ti.xcodeproj/project.pbxproj"
        # Replace LD_RUNPATH_SEARCH_PATHS
        sed -i '' 's/LD_RUNPATH_SEARCH_PATHS = .*;/LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";/' $PLIST_PATH


      - name: Build iOS app
        script: |
          npm run prod:ios

    artifacts:
      - platforms/ios/**/*
